@startuml System C4 Diagram
!include <C4/C4_Context>
!include <C4/C4_Container>

title Система Программной Лояльности

Person(Пользователь, "Пользователь", "Обычный клиент, использующий промокоды и делающий действия")
Person(Бизнес, "Бизнес", "Компания, которая выкладывает промокоды и смотрит статистику")

System(UI, "UI", "Что хотите", "Веб-интерфейс для взаимодействия с системой")

Rel(Пользователь, UI, "Регистрируется и/или входит")
Rel(Пользователь, UI, "Просматривает промокоды и скидки")
Rel(Пользователь, UI, "Ставит лайки и комментирует")
Rel(Пользователь, UI, "Просматривает детали предложений")
Rel(Пользователь, UI, "Использует промокоды")
Rel(Бизнес, UI, "Регистрируется и/или входит в бизнес-аккаунт")
Rel(Бизнес, UI, "Создает и управляет промокодами")
Rel(Бизнес, UI, "Просматривает статистику")


Container(Gateway, "Gateway", "C++", "Маршрутизация запросов к соответствующим сервисам")
Container(AuthService, "Сервис Пользователей", "C++", "Управление пользователями и аутентификация")
Container(PromoService, "Сервис Промокодов", "C++", "Управление промокодами, комментариями и лайками")
Container(StatService, "Сервис Статистики", "C++", "Сбор и анализ статистики")
Container(MessageBroker, "Брокер Сообщений", "C++", "Общий склад для событий")


ContainerDb(AuthDB, "База данных пользователей", "PostgreSQL", "Чтение и запись данных о пользователях, их ролях и аутентификации")
ContainerDb(PromoDB, "База данных постов", "PostgreSQL", "Чтение и запись данных о промокодах, комментариях и лайках")
ContainerDb(StatsDB, "База данных статистики", "ClickHouse",  "Чтение и запись данных о просмотрах, лайках и комментариях")

Rel(UI, Gateway, "gRPC", "Запросы от пользовательского интерфейса")
Rel(Gateway, AuthService, "gRPC", "Запросы для регистрации, аутентификации и управления пользователями")
Rel(Gateway, PromoService, "gRPC", "Запросы для управления промокодами и комментариями")
Rel(Gateway, StatService, "gRPC", "Запросы для получения статистики")
Rel(PromoService, MessageBroker, "gRPC", "Отправка событий (лайки, комментарии, просмотры)")
Rel(MessageBroker, StatService, "gRPC", "Получение событий для анализа")


Rel(AuthService, AuthDB, "JDBC", "Хранение данных пользователей")
Rel(PromoService, PromoDB, "JDBC", "Хранение данных о промокодах и комментариях")
Rel(StatService, StatsDB, "HTTP", "Хранение статистических данных")

@enduml